apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      maxLines: 1000
      derivedFields:
        - name: "Correlation ID"
          matcherRegex: '"correlation_id":\s*"([^"]+)"'
          url: ""
          datasourceUid: ""
        - name: "Service"
          matcherRegex: '"service":\s*"([^"]+)"'
          url: ""
          datasourceUid: ""
